export const titles = {
    LOGO: 'Task Manager',
    SIGN_IN_BTN: 'SIGN IN',
    SIGN_UP_BTN: 'SIGN UP',
    FOOTER: 'footer',
    CREATE_BTN: 'CREATE',
    CREATE_TASK_BTN: 'CREATE TASK',
    SAVE_BTN: 'SAVE',
    DELETE_BTN: 'DELETE',
    EDIT_BTN: 'EDIT',
    GUEST_STATUS: 'GUEST',
    STATUS: 'status',

    USERNAME_INP_PLACEHOLDER: 'some_email@mail.com',
    PASSWORD_INP_PLACEHOLDER: 'Password1234',
    PREMIUM_CODE_INP_PLACEHOLDER: 'Premium code: ****-****-****-****',

    HOME_PAGE_BTN: 'HOME',
    TODO_TITLE: 'TODO',
    IN_PROGRESS_TITLE: 'IN PROGRESS',
    DONE_TITLE: 'DONE',
    ACCEPTED_TITLE: 'ACCEPTED',
    RESET_FILTER_BTN: 'RESET FILTER',
    TAGS_SEARCH_BTN: 'SEARCH',
    TAGS_SEARCH_PLACEHOLDER: 'tag1 tag2 tag3...',
    LOGOUT_BTN: 'LOGOUT',

    TASKMENU_TODO_BTN: 'stage: TODO',
    TASKMENU_IN_PROGRESS_BTN: 'stage: IN PROGRESS',
    TASKMENU_DONE_BTN: 'stage: DONE',
    TASKMENU_ACCEPTED_BTN: 'stage: ACCEPTED',

    CREDIT_TITLE_INP_PLACEHOLDER: 'TASK TITLE',
    CREDIT_DESCRIPTION_INP_PLACEHOLDER: 'TASK DESCRIPTION',
    CREADIT_TYPE_BUG: 'BUG',
    CREADIT_TYPE_STORY: 'STORY',
    CREADIT_TAGS_INP_PLACEHOLDER: 'tag1 tag2 tag3...'
}